spring:
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/students/**
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/enrollments/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

