spring:
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/students/**
